from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class TableEventKind(StrEnum):
    """Kind of event"""

    EMPTY = "empty"
    OCCUPIED = "occupied"
    APPROACH = "approach"


@dataclass(frozen=True)
class BoundingBox:
    """
    A rectangular frame within a video frame. This format is generated by a people detector—a "frame around a person" in an image.
    """

    x1: float
    y1: float
    x2: float
    y2: float

    @property
    def area(self) -> float:
        return max(0.0, self.x2 - self.x1) * max(0.0, self.y2 - self.y1)

    def intersection_area(self, other: "BoundingBox") -> float:
        """The boundaries of the intersection of two frames: the inner rectangle of the overlap"""
        overlap_left = max(self.x1, other.x1)
        overlap_top = max(self.y1, other.y1)
        overlap_right = min(self.x2, other.x2)
        overlap_bottom = min(self.y2, other.y2)

        return max(0.0, overlap_right - overlap_left) * max(
            0.0, overlap_bottom - overlap_top
        )

    def overlaps_table_zone(
        self,
        table_zone: "TableZone",
        min_overlap_ratio: float,
    ) -> bool:
        """
        True if enough of the frame (person) falls within the designated table zone.

        Comparison by the ratio of the area of the person's frame that overlaps with the table zone.
        """
        if self.area <= 1e-6:
            return False
        inter = self.intersection_area(table_zone.to_bounding_box())
        return (inter / self.area) >= min_overlap_ratio


@dataclass(frozen=True)
class TableZone:
    """
    A zone of one table on video: where it is and how big it is.

    Set manually when starting (mouse selection), in the same coordinates as the frame.
    Fields: left upper corner (x, y), width and height of the rectangle.
    """

    x: int
    y: int
    w: int
    h: int

    def __post_init__(self) -> None:
        if self.w <= 0 or self.h <= 0:
            raise ValueError(
                "Table zone not selected: width and height must be greater than zero."
            )

    def to_bounding_box(self) -> BoundingBox:
        """The same area in the format "two opposite corner points" - for comparison with people's frames."""
        return BoundingBox(
            float(self.x),
            float(self.y),
            float(self.x + self.w),
            float(self.y + self.h),
        )


@dataclass(frozen=True)
class TableEvent:
    """One record in the log: frame, time from the start of the video, event type."""

    frame: int
    time_sec: float
    kind: TableEventKind

    @staticmethod
    def at_frame(frame_idx: int, fps: float, kind: TableEventKind) -> "TableEvent":
        return TableEvent(
            frame=frame_idx,
            time_sec=round(frame_idx / fps, 3),
            kind=kind,
        )

    def as_dict(self) -> dict[str, Any]:
        """String for DataFrame / CSV (column event - as before)."""
        return {
            "frame": self.frame,
            "time_sec": self.time_sec,
            "event": self.kind.value,
        }
